var error = {
100:"Data saved succeesfully", 
101:"username/password wrong",
102:"please enter valid input", 
103:"Theater employees added successfully",
104:'Central store employees added successfully',
105:'data already exist',
106:'please enter the itemname',
107:'please enter the itemunit',
108:'Data deleted successfully',
109:'please enter central store name',
110:'please enter central store location',
111:'Data Updated successfully',
112:'Disabled successfully',
113:'please enter theater location',
114:'please enter theater name',
115:'something went wrong',
116:'current password is wrong',
117:"password does not match",
118:"please enter theater",
119:"please enter item",
120:"please enter quantity",
121:"please select item",
122:"Dont have emough item",
123:"closing quantity can not be grater than",
124:"wastage can not be grater than ",
125:"please enter the wastage ammount",
126:"please enter the closing ammount",
127:"addition of both can not be grater than ",
128:"please enter the price paid",
129:"please enter the purchase paid",
130:"Don't have enough cash",
131:"please enter amount",
132:"Cash Issued successfully",
133:"Item Issued successfully",
134:"please enter location",
135:"please enter shift",
136:"Shifts set successfully",
137:"Deleted successfully",
138:"Item already Selected",
139:"End quantity is not correct",
140:"End cash is less than required",
141:"please enter the end cash",
142:"please enter the end quantity",
143:"Password has been sent your registered email id",
144:"Password could not be sent your registered email id!  Please contact admin for password.",
145:"Cpu Not to be empty",
146:"Quantity Not to be empty",
147:"don't have enough cash",
148:"End date can not be greater than start date",
149:"Select Start date",
150:"Select End date",  
151:"Enter end cash",  
151:"Enter end cash",  
152:"Enter Audiance",  
};